sudo: true
language: node_js

before_script:
  # compile the app for testing
  - npm run compile

script:
  # run static/unit testing
  - npm test

  # start the compiled app in the background for non-static testing
  - npm run start:prod &
  - npm run test:a11y
